- name: redis repo file
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: yes

- name: Enable and Install redis
  ansible.builtin.dnf:
    name: '@redis:remi-6.2'
    state: installed

- name: Replace 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start redis
  ansible.builtin.systemd_service:
    state: started
    name: redis
    enabled: true
