- name: Setup ErLang Repo
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

- name: Install RabbitMQ Repos
  ansible.builtin.shell: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

- name: Install ErLang and RabbitMQ
  ansible.builtin.yum:
    name:
      - rabbitmq-server
      - erlang
    state: installed

- name: Add the user Roboshop
  ansible.builtin.user:
    name: roboshop

- name: Start rabbitmq
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: rabbitmq-server

- name: Configuration permission
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: roboshop123
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present


