#    Install MySQL Server
#
#    dnf install mysql-community-server -y
#
#    Start MySQL Service
#
#    systemctl enable mysqld
#    systemctl start mysqld
#
#    Next, We need to change the default root password in order to start using the database service. Use password RoboShop@1 or any other as per your choice.
#
#    mysql_secure_installation --set-root-pass RoboShop@1
#
#    You can check the new password working or not using the following command in MySQL.
#
#    mysql -uroot -pRoboShop@1

- name: Disable mysql 8
  ansible.builtin.shell:  dnf module disable mysql -y

- name: copy mongodb repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name:  Install mysql
  ansible.builtin.dnf:
    name: mysql-community-server
    state: installed

- name: Start mysql
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: mysqld

- name: mysql password
  ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1